### ISSUE TITLE
更新到Squirrel 0.10 部署失败 

### ISSUE THREAD

**Issue by ev6r** [allencch/wubiluna#1]
在MacOS 10.14.2系统下， Squirrel 由0.9更新到0.10 版本，无法重新部署。
wubiluna的信赖模块也都更新了，如何修复？

**Comment by allencch** [comment]
不是很清楚 mac 的运作。能否拿到相关的 log？

**Comment by ev6r** [comment]
E0104 22:16:50.617362 387999168 deployment_tasks.cc:62] Error reading file information: boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/stroke.reverse.bin"
E0104 22:16:50.631611 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/stroke.reverse.bin"
E0104 22:16:50.631726 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/luna_pinyin_simp.prism.bin"
E0104 22:16:50.631803 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/luna_pinyin_tw.prism.bin"
E0104 22:16:50.633616 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/stroke.table.bin"
E0104 22:16:50.634096 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/stroke.prism.bin"
E0104 22:16:50.634594 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/cangjie5.prism.bin"
E0104 22:16:50.634763 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/cangjie5.table.bin"
E0104 22:16:50.636168 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/luna_pinyin.prism.bin"
E0104 22:16:50.636314 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/cangjie5.reverse.bin"
E0104 22:16:50.636445 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/luna_pinyin.reverse.bin"
E0104 22:16:50.636643 101851136 deployment_tasks.cc:488] boost::filesystem::canonical: No such file or directory: "/Users/xwu/Library/Rime/luna_pinyin_fluency.prism.bin"
E0104 22:16:52.071182 101851136 deployment_tasks.cc:319] Error updating schema: nonexistent file '/Users/xwu/Library/Rime/emoji.schema.yaml'.

感觉0.10的版本更新了一些接口

**Comment by allencch** [comment]
不清楚是不是 yaml 的问题。根据以上的 log，貌似各种 bin 文件生成后找不到。我本身是使用 Linux。生成的 bin 是在 `rime/build` 里面。

根据 https://rime.im/release/squirrel/，里头写道：

> 改進部署流程，在 build 子目錄集中存放生成的數據文件

你可以尝试将 `Rime` 里的文件全部删除。建议先做备份。 

若不然，可以尝试在 Squirrel 中提问。

**Comment by ev6r** [comment]
我已经尝试全部删除Rime里的所有内容，重新添加wubiluna以及使用“东风破”安装依赖的包，但是还是部署不成功。从log中来看应该是emoji这个包出现了更新，emoji.schema.yaml这个文件缺失了。

**Comment by ev6r** [comment]
从这里下载了老版本的emoji放到rime目录解决了问题。
https://raw.githubusercontent.com/rime/rime-emoji/schema/emoji.dict.yaml
